### ISSUE TITLE
Request: Tool that attempts to detect the dreaded 'ERB in your assets'

### ISSUE THREAD

**Issue by dpritchett** [capistrano-plugins/capistrano-faster-assets#10]
I'm starting with this, but I don't really know that it's gonna help much:

```sh
find . | grep -E "(css|coffee)"  | xargs -n1 grep "<%"
```

Thoughts?

**Comment by rhomeister** [comment]
Could you elaborate a little about what you're trying to accomplish and why?

**Comment by dpritchett** [comment]
I'd like to use this extension without suffering the caveat in your README.
I work with Spree a lot and there are many files passed through the
pipeline. A method to search my directory tree for probable assets that
include ERB snippets would make it feel safer.

**Comment by rhomeister** [comment]
OK. Clear. Wouldn't it be easier to scan for files with an extension of
.erb instead?

**Comment by dpritchett** [comment]
Maybe I misunderstood the warning.  I was thinking about files that have
inline ERB, not pure ERB files themselves.  Mostly, I don't know what to
look for even though I know how to `find` and `grep`.

**Comment by rhomeister** [comment]
Pretty sure that Javascript and CSS files containing ERB code must have an
.erb extension. Why are you specifically concerned about this problem?
Which symptoms are you experiencing? My advice: don't solve problems that
don't exist (yet).

**Comment by rhomeister** [comment]
Closing due to lack of further input.
