### ISSUE TITLE
should recompile after 'config.action_controller.asset_host' changes

### ISSUE THREAD

**Issue by qhwa** [capistrano-plugins/capistrano-faster-assets#11]
if config.action_controller.asset_host changes to another host, we should recompile assets.

**Comment by rhomeister** [comment]
I might be mistaken, but this is only true if you have .erb files that contain a reference to the asset_host.

**Comment by qhwa** [comment]
You are right @rhomeister 
However it is so common to refer images in the `scss` (likely scss.erb) files.

**Comment by rhomeister** [comment]
OK, clear. The problem with .erb files in general is that they might or might not remain unchanged after recompilation. It is outside the scope of this gem to analyse code in order to detect this. I am going to close this issue, but feel free to reopen if you have new insights.
