### ISSUE TITLE
Push new version to rubygems

### ISSUE THREAD

**Issue by andydust** [capistrano-plugins/capistrano-faster-assets#23]
Many improvements have been pushed to master since the last released version :) particularly this one https://github.com/capistrano-plugins/capistrano-faster-assets/commit/6b243dfe8145f1811f5e646c56b6f947a4ba08b5

**Comment by arturoherrero** [comment]
I think we can close this now 😉 
https://rubygems.org/gems/capistrano-faster-assets/versions/1.1.0
