### ISSUE TITLE
Unconditional compilation

### ISSUE THREAD

**Issue by vassilevsky** [capistrano-plugins/capistrano-faster-assets#7]
Humans are smarter than machines. At least now. Sometimes the developer needs to recompile all assets no matter what. It would be nice if this gem allowed that. Via an environment variable or something like that.

**Comment by NARKOZ** [comment]
Update `Capfile`:

```ruby
require 'capistrano/faster_assets' unless ENV['FORCE_COMPILE']
```

then you can `FORCE_COMPILE=true bundle exec cap deploy`

**Comment by vassilevsky** [comment]
LOL I didn't think of it! :D
